from typing import Any, Dict, Optional


class BaseCallback:
    """Abstract base class for all callbacks."""
    def on_train_begin(self, logs: Optional[Dict[str, Any]] = None): ...
    def on_epoch_end(self, epoch: int, logs: Dict[str, Any]): ...
    def on_train_end(self, logs: Optional[Dict[str, Any]] = None): ...